# Generated by Django 5.2.6 on 2025-09-06 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('laboratory', models.CharField(max_length=100, verbose_name='Лаборатория')),
                ('birth_year', models.IntegerField(verbose_name='Год рождения')),
                ('graduation_year', models.IntegerField(verbose_name='Год окончания вуза')),
                ('academic_degree', models.CharField(blank=True, max_length=100, verbose_name='Ученая степень')),
                ('degree_year', models.IntegerField(blank=True, null=True, verbose_name='Год получения степени')),
                ('status', models.CharField(max_length=100, verbose_name='Статус')),
                ('position', models.CharField(max_length=100, verbose_name='Должность')),
                ('rank', models.CharField(max_length=100, verbose_name='Звание')),
                ('rate', models.CharField(max_length=100, verbose_name='Ставка')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
    ]
